namespace Promezio.OAIAPI.Capabilities.Chat;

/// <summary>
/// Represents a single candidate response generated by the OpenAI chat model for a prompt.
/// </summary>
public class Choice {
    /// <summary>
    /// The numerical index of this choice within the response, where 0 is the best option.
    /// </summary>
    public int? Index { get; set; }
    /// <summary>
    /// The generated text message content for this choice.
    /// </summary>
    public ChatMessage? Message { get; set; }
    // <summary>
    /// The reason why this specific choice was generated, 
    /// such as "stop" for reaching the completion limit or "length" for reaching the desired text length.
    /// </summary>
    public string? Finish_reason { get; set; }
}

