namespace Promezio.OAIAPI.Capabilities.FineTuning;


/// <summary>
/// Represents a fine-tuning operation within the Promezio OAIAPI, capturing various details and states of the fine-tuning process.
/// This class serves as a central object to track and manage the status and parameters of a fine-tuning task.
/// </summary>
public class FineTuningObject {
    /// <summary>
    /// Gets or sets the unique identifier of the fine-tuning operation.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Gets or sets the timestamp indicating when the fine-tuning operation was created, represented as an integer.
    /// </summary>
    public int? Created_at { get; set; }

    /// <summary>
    /// Gets or sets any error that might have occurred during the fine-tuning process.
    /// </summary>
    public TuningError? Error { get; set; }

    /// <summary>
    /// Gets or sets the identifier of the fine-tuned model generated by this operation.
    /// </summary>
    public string? Fine_tuned_model { get; set; }

    /// <summary>
    /// Gets or sets the timestamp indicating when the fine-tuning operation was completed, nullable.
    /// </summary>
    public int? Finished_at { get; set; }

    /// <summary>
    /// Gets or sets the hyperparameters used for the fine-tuning operation.
    /// </summary>
    public Hyperparameters? Hyperparameters { get; set; }

    /// <summary>
    /// Gets or sets the base model used for fine-tuning.
    /// </summary>
    public string? model { get; set; }

    /// <summary>
    /// Gets or sets the type of object, typically used for internal tracking and identification.
    /// </summary>
    public string? Object { get; set; }

    /// <summary>
    /// Gets or sets the identifier of the organization initiating the fine-tuning operation.
    /// </summary>
    public string? Organization_it { get; set; }

    /// <summary>
    /// Gets or sets the array of result file paths or identifiers generated by the fine-tuning operation, nullable.
    /// </summary>
    public string[]? Result_files { get; set; }

    /// <summary>
    /// Gets or sets the current status of the fine-tuning operation (e.g., 'running', 'completed', 'failed').
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Gets or sets the number of tokens trained during the operation, nullable.
    /// </summary>
    public int? Trained_tokens { get; set; }

    /// <summary>
    /// Gets or sets the path or identifier of the training data file used in the fine-tuning operation.
    /// </summary>
    public string? Training_file { get; set; }

    /// <summary>
    /// Gets or sets the path or identifier of the validation data file used in the fine-tuning operation.
    /// </summary>
    public string? Validation_file { get; set; }
}
